name: 'dq_demo'
version: '1.0.0'
config-version: 2

profile: 'dq_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  dbt_dq_tool_schema: DQ_TOOLS_DEMO

# on-run-start:
#   - >
#     {% if target.type == 'duckdb' %}
#       create schema if not exists main;
#     {% endif %}