dq_demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_TEST_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_TEST_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_TEST_ROLE') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_TEST_DATABASE') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_TEST_WAREHOUSE') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dq_tools_integration_tests') }}"
      threads: 10