dq_demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_TEST_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_TEST_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_TEST_ROLE') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_TEST_WAREHOUSE') }}"
      database: dq_tools
      schema: dq_demo_dat
      threads: 10