name: Fake Streamlit Traffic to get app long live

on:
  schedule:
    - cron: '45 1 * * *' # Runs at 01:45. Actions schedules run at most every 5 minutes using UTC time

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: curl ${{ secrets.STREAMLIT_APP_URL_DQC }}
